#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Get the current date in the desired format
date=$(date +"%d-%m-%Y")

# MySQL dump command
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress the dump file
tar -czvf "$date.tar.gz" backup.sql


